import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GeistSans } from "geist/font/sans";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { Provider } from "@/providers/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });
const geist = GeistSans;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Provider>
        <body className={`${geist.className} bg-foreground`}>
          <NavBar />
          <main>{children}</main>
        </body>
      </Provider>
    </html>
  );
}
